## Global Variabel
@BaseUrl = https://pam-2026-p4-ifs23033-be.josua.fun:8080
#@BaseUrl = http://127.0.0.1:8000

## Profile
## ===========================================

### Mengambil semua data tumbuhan
# @name GetProfile
GET {{BaseUrl}}/profile
Content-Type: application/json

### Mengambil photo profil
# @name GetProfilePhoto
GET {{BaseUrl}}/profile/photo
Content-Type: application/json


## Plants
## ===========================================

### Mengambil semua data tumbuhan
# @name GetAllPlants
GET {{BaseUrl}}/plants?search=
Content-Type: application/json

#> {%
#    client.global.set("plantId", response.body.data.plants[0].id);
#    console.log(client.global.get("plantId"))
#%}

### Menambahkan data tumbuhan baru
# @name PostPlants
POST {{BaseUrl}}/plants
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Kangkung
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Brokoli adalah sayuran hijau yang kaya vitamin, mineral, dan serat
--WebAppBoundary
Content-Disposition: form-data; name="manfaat"

Membantu detoksifikasi dan menjaga kesehatan mata
--WebAppBoundary
Content-Disposition: form-data; name="efekSamping"

Dapat menyebabkan kembung
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.png"
Content-Type: image/png

< ./example.png
--WebAppBoundary--

> {%
    client.global.set("plantId", response.body.data.plantId);
    console.log(client.global.get("plantId"))
%}

### Mengambil data tumbuhan berdasarkan id-nya
# @name GetPlantById
GET {{BaseUrl}}/plants/{{plantId}}
Content-Type: application/json

### Melihat gambar tumbuhan
# @name GetPlantImageById
GET {{BaseUrl}}/plants/{{plantId}}/image
Content-Type: application/json

### Mengubah hanya data plant berdasarkan id-nya
# @name PutPlantOnlyData
PUT {{BaseUrl}}/plants/{{plantId}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Brokoli Update
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Brokoli adalah sayuran hijau yang kaya vitamin, mineral, dan serat
--WebAppBoundary
Content-Disposition: form-data; name="manfaat"

Membantu detoksifikasi dan menjaga kesehatan mata
--WebAppBoundary
Content-Disposition: form-data; name="efekSamping"

Dapat menyebabkan kembung
--WebAppBoundary--

### Mengubah gambar dan data plant berdasarkan id-nya
# @name PutPlant
PUT {{BaseUrl}}/plants/{{plantId}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Brokoli
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Brokoli adalah sayuran hijau yang kaya vitamin, mineral, dan serat
--WebAppBoundary
Content-Disposition: form-data; name="manfaat"

Membantu detoksifikasi dan menjaga kesehatan mata
--WebAppBoundary
Content-Disposition: form-data; name="efekSamping"

Dapat menyebabkan kembung
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.png"
Content-Type: image/png

< ./example.png
--WebAppBoundary--

### Menghapus data plant berdasarkan id-nya
# @name DeletePlant
DELETE {{BaseUrl}}/plants/{{plantId}}
Content-Type: application/json


## Watches
## ===========================================

### Mengambil semua data jam tangan
# @name GetAllWatches
GET {{BaseUrl}}/watches?search=
Content-Type: application/json

#> {%
#    client.global.set("watchId", response.body.data.watches[0].id);
#    console.log(client.global.get("watchId"))
#%}

### Menambahkan data jam tangan baru
# @name PostWatch
POST {{BaseUrl}}/watches
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Casio MTP 2026 Edition
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Casio MTP klasik dengan sentuhan modern 2026. Desain minimalis yang cocok untuk acara formal maupun santai.
--WebAppBoundary
Content-Disposition: form-data; name="price"

Rp 750.000
--WebAppBoundary
Content-Disposition: form-data; name="specs"

Diameter 40mm, Quartz Movement, Water Resistant 50M.
--WebAppBoundary
Content-Disposition: form-data; name="features"

Penunjuk tanggal, Jarum Glow in the dark.
--WebAppBoundary
Content-Disposition: form-data; name="material"

Stainless Steel anti karat dengan kaca Mineral Glass.
--WebAppBoundary
Content-Disposition: form-data; name="batteryLife"

Baterai SR626SW (Tahan hingga 3 tahun).
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.png"
Content-Type: image/png

< ./example.png
--WebAppBoundary--

> {%
    client.global.set("watchId", response.body.data.watchId);
    console.log(client.global.get("watchId"))
%}

### Mengambil data jam tangan berdasarkan id-nya
# @name GetWatchById
GET {{BaseUrl}}/watches/{{watchId}}
Content-Type: application/json

### Melihat gambar jam tangan
# @name GetWatchImageById
GET {{BaseUrl}}/watches/{{watchId}}/image
Content-Type: application/json

### Mengubah data jam tangan (Tanpa Gambar)
# @name PutWatchOnlyData
PUT {{BaseUrl}}/watches/{{watchId}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Casio MTP 2026 Edition (Update)
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Casio MTP klasik dengan sentuhan modern 2026. Desain minimalis yang cocok untuk acara formal.
--WebAppBoundary
Content-Disposition: form-data; name="price"

Rp 800.000
--WebAppBoundary
Content-Disposition: form-data; name="specs"

Diameter 40mm, Quartz Movement, Water Resistant 50M.
--WebAppBoundary
Content-Disposition: form-data; name="features"

Penunjuk tanggal, Jarum Glow in the dark.
--WebAppBoundary
Content-Disposition: form-data; name="material"

Stainless Steel anti karat dengan kaca Mineral Glass.
--WebAppBoundary
Content-Disposition: form-data; name="batteryLife"

Baterai SR626SW (Tahan hingga 3 tahun).
--WebAppBoundary--

### Menghapus data jam tangan berdasarkan id-nya
# @name DeleteWatch
DELETE {{BaseUrl}}/watches/{{watchId}}
Content-Type: application/json